name: DP
version: 1.0
main: pkg.main.DeliciousPermissions
description: Provides on-the-fly system for permissions system created by Chirumiru_. But all in memory, and with flat-file saving schedule.
authors:
  - Chirumiru
  - EssentialsTeam
commands:
  setrank:
    description: Moves a player to desired group (Adds to the file if does not exist).
    usage: /<command> <player> <group> | optional [world]
    permissions: dp.setrank
  delply:
    description: Removes any user specific configuration and make them default group.
    usage: /<command> <player>
    permissions: dp.delply
  setsubu:
    description: Adds a group to a user's subgroup list.
    usage: /<command> <player> <group>
    permissions: dp.setsubu
  delsubu:
    description: Removes a group from a user's subgroup list.
    usage: /<command> <player> <group>
    permissions: dp.delsubu
  newgroup:
    description: Adds a group to the system.
    usage: /<command> <group>
    permissions: dp.newgroup
  delgroup:
    description: Removes a group from the system (all its users become default).
    usage: /<command> <group>
    permissions: dp.delgroup
  addpermu:
    description: Adds permissions directly to the user.
    usage: /<command> <player> <permission> [permission2] [permission3]..
    permissions: dp.addpermu
  delpermu:
    description: Removes permissions directly from the user.
    usage: /<command> <player> <permission> [permission2] [permission3]..
    permissions: dp.delpermu
  clearpermu:
    description: Removes all permissions from a user.
    usage: /<command> <player>
    permissions: dp.clearpermu
  listuserperm:
    description: Lists all permissions of a user.
    usage: /<command> <player>
    permissions: dp.listuserperm
  checkuserperm:
    description: Verifies if user has a permission, and where it comes from.
    usage: /<command> <player> <permissions>
    permissions: dp.checkuserperm
  addpermg:
    description: Adds permissions to a group.
    usage: /<command> <group> <permission> [permission2] [permission3]..
    permissions: dp.addpermg
  delpermg:
    description: Removes permissions from a group.
    usage: /<command> <group> <permission> [permission2] [permission3]..
    permissions: dp.delpermg
  clearpermg:
    description: Removes all permissions from a group.
    usage: /<command> <group> <permissions>
    permissions: dp.clearpermg
  listpermg:
    description: Lists all permissions of a group.
    usage: /<command> <group>
    permissions: dp.listpermg
  checkpermg:
    description: Checks if group has a permission and where it comes from.
    usage: /<command> <group> <permissions>
    permissions: dp.checkpermg
  groupaddinheritance:
    description: Adds a group to another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: dp.groupaddinheritance
  groupdelinheritance:
    description: Removes a group from another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: dp.groupdelinheritance
  varaddu:
    description: Adds or replaces a variable of a user (like prefix or suffix).
    usage: /<command> <user> <variable> <value>
    permissions: dp.varaddu
  vardelu:
    description: Removes a variable from a user.
    usage: /<command> <user> <variable>
    permissions: dp.vardelu
  listvaru:
    description: Lists variables of a user (like prefix or suffix).
    usage: /<command> <user>
    permissions: dp.listvaru
  checkvaru:
    description: Verifies a value of a variable of a user, and where it comes from.
    usage: /<command> <user> <variable>
    permissions: dp.checkvaru
  varaddg:
    description: Adds or replaces a variable of a group (like prefix or suffix).
    usage: /<command> <group> <variable> <value>
    permissions: dp.varaddg
  vardelg:
    description: Removes a variable from a group.
    usage: /<command> <group> <variable>
    permissions: dp.vardelg
  listvarg:
    description: Lists variables of a group (like prefix or suffix).
    usage: /<command> <group>
    permissions: dp.listvarg
  checkvarg:
    description: Verifies a value of a variable of a group, and where it comes from.
    usage: /<command> <group> <variable>
    permissions: dp.checkvarg
  whoisthis:
    description: Lists groups and other data of a user.
    usage: /<command> <player>
    permissions: dp.whoisthis
  tempadd:
    description: Creates a temporary permissions copy for a user.
    usage: /<command> <player>
    permissions: dp.tempadd
  tempdel:
    description: Removes the temporary permissions copy for a user.
    usage: /<command> <player>
    permissions: dp.tempdel
  templist:
    description: Lists users in overload-permissions mode made by command /tempadd.
    usage: /<command>
    permissions: dp.templist
  tempdelall:
    description: Removes all overrides made by command /tempadd.
    usage: /<command>
    permissions: dp.tempdelall
  dpsave:
    description: Saves all permissions from server to file.
    usage: /<command>
    permissions: dp.dpsave
  dpload:
    description: Reloads current world and config.yml, or loads given world from file to server.
    usage: /<command> [world]
    permissions: dp.dpload
  listgroups:
    aliases: [manlistg]
    description: Lists the groups available.
    usage: /<command>
    permissions: dp.listgroups
  promote:
    description: Promotes a user in the same heritage line to a higher rank.
    usage: /<command> <player> <group>
    permissions: dp.promote
  demote:
    description: Demotes a user in the same heritage line to a lower rank.
    usage: /<command> <player> <group>
    permissions: dp.demote
  togglevalidate:
    description: Toggles on/off the validating if user is online.
    usage: /<command>
    permissions: dp.togglevalidate
  togglesave:
    description: Toggles on/off the autosave.
    usage: /<command>
    permissions: dp.togglesave
  dpworld:
    description: Prints the selected world name.
    usage: /<command>
    permissions: dp.dpworld
  dpselect:
    description: Selects a world to work with commands.
    usage: /<command> <world>
    permissions: dp.dpselect
  dpclear:
    description: Clears world selection. Commands will work on your current world.
    usage: /<command>
    permissions: dp.dpclear
  dpcheckw:
    description: Obtains the path to each file a world is storing its data in (users/groups).
    usage: /<command> <world>
    permissions: dp.dpcheckw
    
Permissions:
    dp.op:
        description: User is treated as an op when using the GroupManager commands.
        default: false
